{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dockyard.fullname" . }}
  labels:
    {{- include "dockyard.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "dockyard.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      {{- if ne ((.Values.tls).mode | default "off") "off" }}
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      {{- end }}
{{- end }}
