provider "aws" {
  region = var.aws_region
}

# Points at an existing kubeconfig context by default — set kube_config_path
# / kube_context if you're not deploying to the cluster your current
# kubectl context already targets (e.g. in CI, where a kubeconfig is
# generated by a previous step).
provider "kubernetes" {
  config_path    = var.kube_config_path
  config_context = var.kube_context
}

provider "helm" {
  kubernetes {
    config_path    = var.kube_config_path
    config_context = var.kube_context
  }
}
