package config

import (
	"os"
	"strconv"
	"strings"

	_ "github.com/joho/godotenv/autoload"
)

type StorageBackend string

const (
	StorageLocal StorageBackend = "local"
	StorageS3    StorageBackend = "s3"
)

type Config struct {
	Port int

	RegistryMode string

	StoragePath string

	RegistryURL      string
	RegistryUsername string
	RegistryPassword string

	StorageBackend StorageBackend

	S3Endpoint  string
	S3AccessKey string
	S3SecretKey string
	S3Bucket    string
	S3Region    string
	S3Secure    bool

	AuthUsername      string
	AuthPassword      string
	JWTSecret         string
	JWTSecretPrevious string
	V2AuthEnabled     bool
	V2AnonymousPull   bool

	// CORSAllowedOrigins is empty by default: the UI is embedded and served
	// same-origin, so no cross-origin access is needed at all.
	CORSAllowedOrigins []string
	// RateLimitLoginPerMin throttles login + /v2/token per client IP
	// (brute-force protection). 0 disables.
	RateLimitLoginPerMin int
	// RateLimitGlobalRPS is a loose per-IP requests/second cap on everything
	// else. 0 disables.
	RateLimitGlobalRPS int

	// Native TLS: off (default, plain HTTP — put a reverse proxy in front),
	// static (TLS_CERT_FILE/TLS_KEY_FILE), self-signed (autogenerated,
	// persisted under <StoragePath>/tls), acme (Let's Encrypt via TLS-ALPN —
	// requires the server reachable on :443 and TLS_DOMAIN set).
	TLSMode      string
	TLSCertFile  string
	TLSKeyFile   string
	TLSDomain    string
	TLSACMEEmail string
}

func Load() *Config {
	port, _ := strconv.Atoi(getEnv("PORT", "8080"))
	return &Config{
		Port:             port,
		RegistryMode:     getEnv("REGISTRY_MODE", "embedded"),
		StoragePath:      getEnv("REGISTRY_STORAGE_PATH", "./data/registry"),
		RegistryURL:      getEnv("REGISTRY_URL", ""),
		RegistryUsername: getEnv("REGISTRY_USERNAME", ""),
		RegistryPassword: getEnv("REGISTRY_PASSWORD", ""),
		StorageBackend:   StorageBackend(getEnv("REGISTRY_STORAGE_BACKEND", "local")),
		S3Endpoint:       getEnv("S3_ENDPOINT", ""),
		S3AccessKey:      getEnv("S3_ACCESS_KEY", ""),
		S3SecretKey:      getEnv("S3_SECRET_KEY", ""),
		S3Bucket:         getEnv("S3_BUCKET", "dockyard-registry"),
		S3Region:         getEnv("S3_REGION", "us-east-1"),
		S3Secure:         getEnv("S3_SECURE", "false") == "true",
		AuthUsername: getEnv("AUTH_USERNAME", ""),
		AuthPassword: getEnv("AUTH_PASSWORD", ""),
		JWTSecret:    getEnv("JWT_SECRET", ""),
		// Rotation: set JWT_SECRET to the new value and JWT_SECRET_PREVIOUS to
		// the old one; tokens signed with either verify until the grace window
		// ends (remove JWT_SECRET_PREVIOUS afterwards).
		JWTSecretPrevious: getEnv("JWT_SECRET_PREVIOUS", ""),
		// BREAKING (since the RBAC release): /v2/* now requires auth by
		// default. Set V2_AUTH_ENABLED=false to restore the old open registry,
		// or V2_ANONYMOUS_PULL=true for a public-read registry.
		V2AuthEnabled:   getEnv("V2_AUTH_ENABLED", "true") == "true",
		V2AnonymousPull: getEnv("V2_ANONYMOUS_PULL", "false") == "true",

		CORSAllowedOrigins:   splitList(getEnv("CORS_ALLOWED_ORIGINS", "")),
		RateLimitLoginPerMin: getEnvInt("RATE_LIMIT_LOGIN_PER_MIN", 10),
		RateLimitGlobalRPS:   getEnvInt("RATE_LIMIT_GLOBAL_RPS", 100),

		TLSMode:      getEnv("TLS_MODE", "off"),
		TLSCertFile:  getEnv("TLS_CERT_FILE", ""),
		TLSKeyFile:   getEnv("TLS_KEY_FILE", ""),
		TLSDomain:    getEnv("TLS_DOMAIN", ""),
		TLSACMEEmail: getEnv("TLS_ACME_EMAIL", ""),
	}
}

func getEnvInt(key string, fallback int) int {
	if v := os.Getenv(key); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			return n
		}
	}
	return fallback
}

func splitList(raw string) []string {
	if raw == "" {
		return nil
	}
	var out []string
	for part := range strings.SplitSeq(raw, ",") {
		if p := strings.TrimSpace(part); p != "" {
			out = append(out, p)
		}
	}
	return out
}

func getEnv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
